default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  alchemy_api_key: "3d3c2ec83468548b347ec0585437b0c960a0ea29"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
